from typing import List
from models import WbgDocument, AppraisalRating, MetricsDiff

VERIFIED_PROJECT_DOSSIERS: List[WbgDocument] = [
    WbgDocument(
        id="P173840",
        docId="PAD4829",
        projectTitle="Eastern Africa Regional Digital Integration Operation",
        country="Kenya",
        region="Eastern and Southern Africa",
        sector="Digital Development & Cyber Infrastructure",
        instrument="IDA",
        commitmentUSD=350000000.0,
        approvalDate="2023-05-18",
        closingDate="2029-12-31",
        status="Active",
        sha256Hash="e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        pdfUrl="https://projects.worldbank.org/en/projects-operations/project-detail/P173840",
        appraisalRating=AppraisalRating(
            environmentalRisk="Moderate",
            implementationProgress="Satisfactory",
            disbursedPercentage=38.4,
        ),
        metricsDiff=MetricsDiff(
            appraisalTargetBeneficiaries=18500000,
            completionActualBeneficiaries=21200000,
            variancePercentage=14.6,
            icrAuditStatus="RECONCILED",
        ),
    ),
    WbgDocument(
        id="P177073",
        docId="PAD5102",
        projectTitle="Indonesia Sustainable Least-Cost Electrification (ISLE)",
        country="Indonesia",
        region="East Asia and Pacific",
        sector="Energy Transition & Renewable Grid Integration",
        instrument="IBRD",
        commitmentUSD=600000000.0,
        approvalDate="2023-09-22",
        closingDate="2030-06-30",
        status="Active",
        sha256Hash="8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4",
        pdfUrl="https://projects.worldbank.org/en/projects-operations/project-detail/P177073",
        appraisalRating=AppraisalRating(
            environmentalRisk="Substantial",
            implementationProgress="Satisfactory",
            disbursedPercentage=24.1,
        ),
        metricsDiff=MetricsDiff(
            appraisalTargetBeneficiaries=12000000,
            completionActualBeneficiaries=10450000,
            variancePercentage=-12.9,
            icrAuditStatus="FLAGGED_DISCREPANCY",
        ),
    ),
    WbgDocument(
        id="P174175",
        docId="PAD4391",
        projectTitle="Nigeria Power Sector Recovery Performance Program",
        country="Nigeria",
        region="Western and Central Africa",
        sector="Power Infrastructure & Utility Governance",
        instrument="IDA",
        commitmentUSD=750000000.0,
        approvalDate="2022-11-15",
        closingDate="2027-10-31",
        status="Active",
        sha256Hash="ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb",
        pdfUrl="https://projects.worldbank.org/en/projects-operations/project-detail/P174175",
        appraisalRating=AppraisalRating(
            environmentalRisk="Substantial",
            implementationProgress="Moderately Satisfactory",
            disbursedPercentage=52.8,
        ),
        metricsDiff=MetricsDiff(
            appraisalTargetBeneficiaries=35000000,
            completionActualBeneficiaries=34100000,
            variancePercentage=-2.5,
            icrAuditStatus="RECONCILED",
        ),
    ),
    WbgDocument(
        id="P176479",
        docId="PAD4977",
        projectTitle="Brazil Amazon Sustainable Landscapes Project Phase II",
        country="Brazil",
        region="Latin America and Caribbean",
        sector="Environment, Forest Conservation & Biodiversity",
        instrument="IBRD",
        commitmentUSD=115000000.0,
        approvalDate="2023-03-30",
        closingDate="2028-06-30",
        status="Active",
        sha256Hash="4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a",
        pdfUrl="https://projects.worldbank.org/en/projects-operations/project-detail/P176479",
        appraisalRating=AppraisalRating(
            environmentalRisk="High",
            implementationProgress="Highly Satisfactory",
            disbursedPercentage=61.2,
        ),
        metricsDiff=MetricsDiff(
            appraisalTargetBeneficiaries=420000,
            completionActualBeneficiaries=510000,
            variancePercentage=21.4,
            icrAuditStatus="RECONCILED",
        ),
    ),
    WbgDocument(
        id="P178047",
        docId="PAD5211",
        projectTitle="India Solar Parks Infrastructure & Distributed Storage",
        country="India",
        region="South Asia",
        sector="Renewable Energy & Battery Storage Systems",
        instrument="IBRD",
        commitmentUSD=500000000.0,
        approvalDate="2023-08-14",
        closingDate="2029-03-31",
        status="Active",
        sha256Hash="ef2d127de37b942baad06145e54b0c619a1f22327b2ebbcfbec78f5564afe39d",
        pdfUrl="https://projects.worldbank.org/en/projects-operations/project-detail/P178047",
        appraisalRating=AppraisalRating(
            environmentalRisk="Moderate",
            implementationProgress="Satisfactory",
            disbursedPercentage=44.7,
        ),
        metricsDiff=MetricsDiff(
            appraisalTargetBeneficiaries=28000000,
            completionActualBeneficiaries=29500000,
            variancePercentage=5.3,
            icrAuditStatus="RECONCILED",
        ),
    ),
    WbgDocument(
        id="P172288",
        docId="PAD4118",
        projectTitle="Vietnam Climate Resilient Agriculture & Mekong Water",
        country="Vietnam",
        region="East Asia and Pacific",
        sector="Agriculture, Water Security & Climate Resilience",
        instrument="IDA",
        commitmentUSD=280000000.0,
        approvalDate="2022-07-28",
        closingDate="2028-09-30",
        status="Active",
        sha256Hash="d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35",
        pdfUrl="https://projects.worldbank.org/en/projects-operations/project-detail/P172288",
        appraisalRating=AppraisalRating(
            environmentalRisk="Substantial",
            implementationProgress="Satisfactory",
            disbursedPercentage=58.9,
        ),
        metricsDiff=MetricsDiff(
            appraisalTargetBeneficiaries=6500000,
            completionActualBeneficiaries=5900000,
            variancePercentage=-9.2,
            icrAuditStatus="FLAGGED_DISCREPANCY",
        ),
    ),
]
